"""Remove audio features from Song model

Revision ID: 3898c1944ac6
Revises: 39875c86b0f0
Create Date: 2025-04-29 18:14:10.190630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3898c1944ac6'
down_revision = '39875c86b0f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('liveness')
        batch_op.drop_column('key')
        batch_op.drop_column('acousticness')
        batch_op.drop_column('loudness')
        batch_op.drop_column('instrumentalness')
        batch_op.drop_column('danceability')
        batch_op.drop_column('energy')
        batch_op.drop_column('speechiness')
        batch_op.drop_column('valence')
        batch_op.drop_column('tempo')
        batch_op.drop_column('mode')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('tempo', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('valence', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('speechiness', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('energy', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('danceability', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('instrumentalness', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('loudness', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('acousticness', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('key', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('liveness', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
