"""Add audio features to Song model

Revision ID: 39875c86b0f0
Revises: 6d9d946e3851
Create Date: 2025-04-29 18:10:05.757799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39875c86b0f0'
down_revision = '6d9d946e3851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('popularity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duration_ms', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('explicit', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('danceability', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('energy', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('key', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('loudness', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('mode', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('speechiness', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('acousticness', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('instrumentalness', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('liveness', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tempo', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_column('tempo')
        batch_op.drop_column('valence')
        batch_op.drop_column('liveness')
        batch_op.drop_column('instrumentalness')
        batch_op.drop_column('acousticness')
        batch_op.drop_column('speechiness')
        batch_op.drop_column('mode')
        batch_op.drop_column('loudness')
        batch_op.drop_column('key')
        batch_op.drop_column('energy')
        batch_op.drop_column('danceability')
        batch_op.drop_column('release_date')
        batch_op.drop_column('explicit')
        batch_op.drop_column('duration_ms')
        batch_op.drop_column('popularity')

    # ### end Alembic commands ###
